# Generated by Django 2.2.4 on 2020-09-13 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_step_no', models.CharField(max_length=200, verbose_name='测试步聚序号')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='测试步骤描述')),
                ('locator_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='定位方式')),
                ('locator_exp', models.CharField(blank=True, max_length=800, null=True, verbose_name='定位表达式')),
                ('test_data', models.CharField(blank=True, max_length=200, null=True, verbose_name='测试数据值')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试用例步骤表',
                'verbose_name_plural': '测试用例步骤表',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='关键字名称')),
                ('params', models.CharField(max_length=300, null=True, verbose_name='关键字参数说明')),
                ('desc', models.TextField(null=True, verbose_name='关键字用途描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关键字表',
                'verbose_name_plural': '关键字表',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('test_owner', models.CharField(max_length=50, verbose_name='测试负责人')),
                ('desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.Project')),
            ],
            options={
                'verbose_name': '模块信息表',
                'verbose_name_plural': '模块信息表',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='测试用例名称')),
                ('author', models.CharField(max_length=20, verbose_name='编写人员')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_module', smart_selects.db_fields.GroupedForeignKey(group_field='belong_project', on_delete=django.db.models.deletion.CASCADE, to='auto_test.Module', verbose_name='所属模块')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
            },
        ),
        migrations.CreateModel(
            name='TestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(help_text='0：表示未执行，1：表示已执行', null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exception_info', models.CharField(blank=True, max_length=500, null=True)),
                ('capture_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试用例结果记录表',
                'verbose_name_plural': '测试用例结果记录表',
            },
        ),
        migrations.CreateModel(
            name='TestCaseStepExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行结果')),
                ('exception_info', models.CharField(blank=True, max_length=500, null=True)),
                ('capture_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('case_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.CaseStep', verbose_name='测试步骤id')),
                ('test_case_execute_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCaseExecuteRecord', verbose_name='执行id')),
            ],
            options={
                'verbose_name': '测试用例步骤执行结果表',
                'verbose_name_plural': '测试用例步骤执行结果表',
            },
        ),
        migrations.AddField(
            model_name='casestep',
            name='key_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_test.KeyWord', verbose_name='操作关键字'),
        ),
        migrations.AddField(
            model_name='casestep',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='用例名称'),
        ),
    ]
