# Generated by Django 2.2.4 on 2020-09-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0002_auto_20200913_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试集合',
                'verbose_name_plural': '测试集合',
            },
        ),
        migrations.CreateModel(
            name='TestSuitExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_time_interval', models.IntegerField(default=0, null=True, verbose_name='延迟时间')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuit', verbose_name='测试集合')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuitTestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('exception_info', models.CharField(blank=True, max_length=500, null=True)),
                ('capture_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='执行的测试用例')),
                ('test_suit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuitExecuteRecord', verbose_name='执行的测试集合执行记录')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuitTestStepExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_desc', models.CharField(max_length=300)),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行结果')),
                ('exception_info', models.CharField(blank=True, max_length=500, null=True)),
                ('capture_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.CaseStep', verbose_name='测试步骤id')),
                ('test_case_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuitTestCaseExecuteRecord', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '用例步骤执行结果表',
                'verbose_name_plural': '用例步骤执行结果表',
            },
        ),
        migrations.CreateModel(
            name='TestSuitTestCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(default=1, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='测试用例')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuit', verbose_name='测试集合')),
            ],
        ),
    ]
